apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::076887163641:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-1AAQ5SU866EC5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::076887163641:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T07:05:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1836"
  uid: fdfc951f-504b-40f6-8729-b0ad1a624ac5
